# Generated by Django 5.0.6 on 2024-07-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warehouse_Name', models.CharField(max_length=100)),
                ('Warehouse_location', models.CharField(max_length=100)),
                ('no_of_floors_available', models.IntegerField()),
                ('Warehouse_square_feet', models.IntegerField()),
                ('Warehouse_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Warehouse_image', models.ImageField(blank=True, null=True, upload_to='warehouse_images/')),
                ('Additional_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('permitted_items', models.TextField(default='[]')),
                ('prohibited_items', models.TextField(default='[]')),
            ],
        ),
    ]
