# Generated by Django 5.0.6 on 2024-07-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedetails',
            name='first_floor_square_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousedetails',
            name='ground_floor_square_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehousedetails',
            name='no_of_floors_available',
            field=models.CharField(choices=[('Ground', 'Ground Floor'), ('First', 'First Floor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='warehousedetails',
            name='permitted_items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='warehousedetails',
            name='prohibited_items',
            field=models.JSONField(default=list),
        ),
    ]
