# Generated by Django 5.0.6 on 2024-08-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse_Management', '0002_warehousedetails_first_floor_square_feet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
